---
- name: SECURE SSH
  become: true
  hosts: all
  tasks: 
    - name: Disable Root Login for SSH
      community.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'
        state: present

    - name: List of AllowUsers
      community.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^AllowUsers'
        line: 'AllowUsers {{ listOfAllowUsers | join(" ") }}'
        state: present
      with_items: "{{ listOfAllowUsers }}"
