- name: Install UFW
  apt:
    name: ufw
    state: present

- name: Enable UFW service
  systemd:
    name: ufw
    state: started
    enabled: true
  register: ufw_check

- name: Debug UFW service status
  debug:
    msg: "The value of ufw_check is {{ ufw_check }}"

- name: Deny HTTP port (80)
  community.general.ufw:
    rule: deny
    port: "80"

- name: Allow SSH port (22)
  community.general.ufw:
    rule: allow
    port: "22"

- name: Deny Telnet port (23)
  community.general.ufw:
    rule: deny
    port: "23"
