---
- name: Saved fail2ban config
  shell: cp /etc/fail2ban/jail.conf /etc/fail2ban/jail.local

- name: Read the config file
  slurp:
    src: /etc/fail2ban/jail.local
  register: file_content


- name: Replace the entire [ssh] section
  blockinfile:
    path: /etc/fail2ban/jail.local
    marker: "# {mark} FAIL2BAN SSH CONFIG"
    block: |
      [ssh]
      enabled = true
      port = ssh
      logpath = /var/log/custom_auth.log
      maxretry = "{{ fail2ban_max_try }}"

- name: Ensure fail2ban is enabled and started
  service:
    name: fail2ban
    state: restarted
    enabled: yes
