---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install Fail2Ban
  ansible.builtin.apt:
    name: fail2ban
    state: present

- name: Ensure Fail2Ban is enabled and running
  ansible.builtin.systemd:
    name: fail2ban
    state: started
    enabled: true

- name: Wait for Fail2Ban to be fully initialized
  wait_for:
    timeout: 5

- name: Gather service facts
  service_facts:

- name: Fail if Fail2Ban is not running or enabled
  fail:
    msg: "Fail2Ban is not running or not enabled!"
  when:
    - ansible_facts.services['fail2ban.service'].state != 'running'
    - not ansible_facts.services['fail2ban.service'].enabled
