---
- name: Update repositories cache and install apache2 package
  ansible.builtin.apt:
    name: apache2
    update_cache: yes

- name: start apache2 service if is not started
  ansible.builtin.systemd:
    name: apache2
    state: started
